/**
 * pax/v1/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { V1Sample } from './v1Sample';


export interface V1Data { 
    deviceId?: string;
    deviceName?: string;
    lat?: number;
    lon?: number;
    samples?: Array<V1Sample>;
}

