/**
 * pax/v1/service.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface V1Sample { 
    deviceId?: string;
    messageId?: string;
    timestamp?: string;
    bluetoothCount?: number;
    wifiCount?: number;
    seq?: number;
    uptimeSeconds?: number;
    coreTemperature?: number;
}

